config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :books
  root 'books#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :find_book, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @books = Book.all.order('created_at DESC')
  end

  def new
    @book = current_user.books.build
  end

  def show; end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to root_path, notice: 'Successfully created new Book'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated'
    else
      render 'edit'
  end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :publisher, :year, :place, :author, :description)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', link: @book %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
  <h1>Your favorite Books</h1>
  <p><%= link_to "Sing up to submit book", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
</div>
<% end %>


<% @books.each do |book| %>
<h2><%= book.title %></h2>
<h2><%= book.year %></h2>
<br>
<%= link_to "Read Book", book %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' %>

<%= link_to "back", root_path %>

app/views/books/show.html.erb
<div> <h3>Title : <%= @book.title %></h3></div>
<h3>Publisher : <%= @book.publisher %></h3>
<h3>Year :<%= @book.year %></h3>
<h3>Place :<%= @book.place %></h3>
<h3>Author :<%= @book.author %></h3>
<div>
	<h3>Description :</h3>
	<%= @book.description %>
</div>
<br>
<h5> Submited by :- <%= @book.user.email %></h5>
<% if @book.user == current_user %>
<br>
<%= link_to "Back", root_path %>
<br>
<%= link_to "Edit Book", edit_book_path(@book) %>
<br>
<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm:"Are you sure?" } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookAuthor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


  <body>

          <%= link_to "Book", root_path %>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Submit Book', new_book_path %></li>
              <li><%= link_to 'Account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
          <% end %>
    <%= yield %>
  </body>
</html>